/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as AuthSignUpImport } from './routes/_auth/sign-up'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as ProtectedDashboardOrgOrgIdIndexImport } from './routes/_protected/dashboard/org/$orgId/index'
import { Route as ProtectedDashboardOrgOrgIdUserUserIdImport } from './routes/_protected/dashboard/org/$orgId/user/$userId'

// Create Virtual Routes

const ProtectedDashboardIndexLazyImport = createFileRoute(
  '/_protected/dashboard/',
)()
const ProtectedDashboardTranscribeLazyImport = createFileRoute(
  '/_protected/dashboard/transcribe',
)()
const ProtectedDashboardNotesLazyImport = createFileRoute(
  '/_protected/dashboard/notes',
)()
const ProtectedDashboardChatLazyImport = createFileRoute(
  '/_protected/dashboard/chat',
)()
const ProtectedDashboardCanvasLazyImport = createFileRoute(
  '/_protected/dashboard/canvas',
)()
const ProtectedDashboardAudioLazyImport = createFileRoute(
  '/_protected/dashboard/audio',
)()
const ProtectedDashboardAccountLazyImport = createFileRoute(
  '/_protected/dashboard/account',
)()

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardIndexLazyRoute =
  ProtectedDashboardIndexLazyImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/index.lazy').then((d) => d.Route),
  )

const ProtectedDashboardTranscribeLazyRoute =
  ProtectedDashboardTranscribeLazyImport.update({
    id: '/dashboard/transcribe',
    path: '/dashboard/transcribe',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/transcribe.lazy').then(
      (d) => d.Route,
    ),
  )

const ProtectedDashboardNotesLazyRoute =
  ProtectedDashboardNotesLazyImport.update({
    id: '/dashboard/notes',
    path: '/dashboard/notes',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/notes.lazy').then((d) => d.Route),
  )

const ProtectedDashboardChatLazyRoute = ProtectedDashboardChatLazyImport.update(
  {
    id: '/dashboard/chat',
    path: '/dashboard/chat',
    getParentRoute: () => ProtectedRoute,
  } as any,
).lazy(() =>
  import('./routes/_protected/dashboard/chat.lazy').then((d) => d.Route),
)

const ProtectedDashboardCanvasLazyRoute =
  ProtectedDashboardCanvasLazyImport.update({
    id: '/dashboard/canvas',
    path: '/dashboard/canvas',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/canvas.lazy').then((d) => d.Route),
  )

const ProtectedDashboardAudioLazyRoute =
  ProtectedDashboardAudioLazyImport.update({
    id: '/dashboard/audio',
    path: '/dashboard/audio',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/audio.lazy').then((d) => d.Route),
  )

const ProtectedDashboardAccountLazyRoute =
  ProtectedDashboardAccountLazyImport.update({
    id: '/dashboard/account',
    path: '/dashboard/account',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/account.lazy').then((d) => d.Route),
  )

const ProtectedDashboardOrgOrgIdIndexRoute =
  ProtectedDashboardOrgOrgIdIndexImport.update({
    id: '/dashboard/org/$orgId/',
    path: '/dashboard/org/$orgId/',
    getParentRoute: () => ProtectedRoute,
  } as any)

const ProtectedDashboardOrgOrgIdUserUserIdRoute =
  ProtectedDashboardOrgOrgIdUserUserIdImport.update({
    id: '/dashboard/org/$orgId/user/$userId',
    path: '/dashboard/org/$orgId/user/$userId',
    getParentRoute: () => ProtectedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/_protected/dashboard/account': {
      id: '/_protected/dashboard/account'
      path: '/dashboard/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof ProtectedDashboardAccountLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/audio': {
      id: '/_protected/dashboard/audio'
      path: '/dashboard/audio'
      fullPath: '/dashboard/audio'
      preLoaderRoute: typeof ProtectedDashboardAudioLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/canvas': {
      id: '/_protected/dashboard/canvas'
      path: '/dashboard/canvas'
      fullPath: '/dashboard/canvas'
      preLoaderRoute: typeof ProtectedDashboardCanvasLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/chat': {
      id: '/_protected/dashboard/chat'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof ProtectedDashboardChatLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/notes': {
      id: '/_protected/dashboard/notes'
      path: '/dashboard/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof ProtectedDashboardNotesLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/transcribe': {
      id: '/_protected/dashboard/transcribe'
      path: '/dashboard/transcribe'
      fullPath: '/dashboard/transcribe'
      preLoaderRoute: typeof ProtectedDashboardTranscribeLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/org/$orgId/': {
      id: '/_protected/dashboard/org/$orgId/'
      path: '/dashboard/org/$orgId'
      fullPath: '/dashboard/org/$orgId'
      preLoaderRoute: typeof ProtectedDashboardOrgOrgIdIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/org/$orgId/user/$userId': {
      id: '/_protected/dashboard/org/$orgId/user/$userId'
      path: '/dashboard/org/$orgId/user/$userId'
      fullPath: '/dashboard/org/$orgId/user/$userId'
      preLoaderRoute: typeof ProtectedDashboardOrgOrgIdUserUserIdImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteChildren {
  ProtectedDashboardAccountLazyRoute: typeof ProtectedDashboardAccountLazyRoute
  ProtectedDashboardAudioLazyRoute: typeof ProtectedDashboardAudioLazyRoute
  ProtectedDashboardCanvasLazyRoute: typeof ProtectedDashboardCanvasLazyRoute
  ProtectedDashboardChatLazyRoute: typeof ProtectedDashboardChatLazyRoute
  ProtectedDashboardNotesLazyRoute: typeof ProtectedDashboardNotesLazyRoute
  ProtectedDashboardTranscribeLazyRoute: typeof ProtectedDashboardTranscribeLazyRoute
  ProtectedDashboardIndexLazyRoute: typeof ProtectedDashboardIndexLazyRoute
  ProtectedDashboardOrgOrgIdIndexRoute: typeof ProtectedDashboardOrgOrgIdIndexRoute
  ProtectedDashboardOrgOrgIdUserUserIdRoute: typeof ProtectedDashboardOrgOrgIdUserUserIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardAccountLazyRoute: ProtectedDashboardAccountLazyRoute,
  ProtectedDashboardAudioLazyRoute: ProtectedDashboardAudioLazyRoute,
  ProtectedDashboardCanvasLazyRoute: ProtectedDashboardCanvasLazyRoute,
  ProtectedDashboardChatLazyRoute: ProtectedDashboardChatLazyRoute,
  ProtectedDashboardNotesLazyRoute: ProtectedDashboardNotesLazyRoute,
  ProtectedDashboardTranscribeLazyRoute: ProtectedDashboardTranscribeLazyRoute,
  ProtectedDashboardIndexLazyRoute: ProtectedDashboardIndexLazyRoute,
  ProtectedDashboardOrgOrgIdIndexRoute: ProtectedDashboardOrgOrgIdIndexRoute,
  ProtectedDashboardOrgOrgIdUserUserIdRoute:
    ProtectedDashboardOrgOrgIdUserUserIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/account': typeof ProtectedDashboardAccountLazyRoute
  '/dashboard/audio': typeof ProtectedDashboardAudioLazyRoute
  '/dashboard/canvas': typeof ProtectedDashboardCanvasLazyRoute
  '/dashboard/chat': typeof ProtectedDashboardChatLazyRoute
  '/dashboard/notes': typeof ProtectedDashboardNotesLazyRoute
  '/dashboard/transcribe': typeof ProtectedDashboardTranscribeLazyRoute
  '/dashboard': typeof ProtectedDashboardIndexLazyRoute
  '/dashboard/org/$orgId': typeof ProtectedDashboardOrgOrgIdIndexRoute
  '/dashboard/org/$orgId/user/$userId': typeof ProtectedDashboardOrgOrgIdUserUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/account': typeof ProtectedDashboardAccountLazyRoute
  '/dashboard/audio': typeof ProtectedDashboardAudioLazyRoute
  '/dashboard/canvas': typeof ProtectedDashboardCanvasLazyRoute
  '/dashboard/chat': typeof ProtectedDashboardChatLazyRoute
  '/dashboard/notes': typeof ProtectedDashboardNotesLazyRoute
  '/dashboard/transcribe': typeof ProtectedDashboardTranscribeLazyRoute
  '/dashboard': typeof ProtectedDashboardIndexLazyRoute
  '/dashboard/org/$orgId': typeof ProtectedDashboardOrgOrgIdIndexRoute
  '/dashboard/org/$orgId/user/$userId': typeof ProtectedDashboardOrgOrgIdUserUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_protected/dashboard/account': typeof ProtectedDashboardAccountLazyRoute
  '/_protected/dashboard/audio': typeof ProtectedDashboardAudioLazyRoute
  '/_protected/dashboard/canvas': typeof ProtectedDashboardCanvasLazyRoute
  '/_protected/dashboard/chat': typeof ProtectedDashboardChatLazyRoute
  '/_protected/dashboard/notes': typeof ProtectedDashboardNotesLazyRoute
  '/_protected/dashboard/transcribe': typeof ProtectedDashboardTranscribeLazyRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexLazyRoute
  '/_protected/dashboard/org/$orgId/': typeof ProtectedDashboardOrgOrgIdIndexRoute
  '/_protected/dashboard/org/$orgId/user/$userId': typeof ProtectedDashboardOrgOrgIdUserUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/demo/tanstack-query'
    | '/dashboard/account'
    | '/dashboard/audio'
    | '/dashboard/canvas'
    | '/dashboard/chat'
    | '/dashboard/notes'
    | '/dashboard/transcribe'
    | '/dashboard'
    | '/dashboard/org/$orgId'
    | '/dashboard/org/$orgId/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/demo/tanstack-query'
    | '/dashboard/account'
    | '/dashboard/audio'
    | '/dashboard/canvas'
    | '/dashboard/chat'
    | '/dashboard/notes'
    | '/dashboard/transcribe'
    | '/dashboard'
    | '/dashboard/org/$orgId'
    | '/dashboard/org/$orgId/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/demo/tanstack-query'
    | '/_protected/dashboard/account'
    | '/_protected/dashboard/audio'
    | '/_protected/dashboard/canvas'
    | '/_protected/dashboard/chat'
    | '/_protected/dashboard/notes'
    | '/_protected/dashboard/transcribe'
    | '/_protected/dashboard/'
    | '/_protected/dashboard/org/$orgId/'
    | '/_protected/dashboard/org/$orgId/user/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/_auth/forgot-password",
        "/_auth/reset-password",
        "/_auth/sign-in",
        "/_auth/sign-up",
        "/demo/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/dashboard/account",
        "/_protected/dashboard/audio",
        "/_protected/dashboard/canvas",
        "/_protected/dashboard/chat",
        "/_protected/dashboard/notes",
        "/_protected/dashboard/transcribe",
        "/_protected/dashboard/",
        "/_protected/dashboard/org/$orgId/",
        "/_protected/dashboard/org/$orgId/user/$userId"
      ]
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx"
    },
    "/_auth/reset-password": {
      "filePath": "_auth/reset-password.tsx"
    },
    "/_auth/sign-in": {
      "filePath": "_auth/sign-in.tsx"
    },
    "/_auth/sign-up": {
      "filePath": "_auth/sign-up.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/_protected/dashboard/account": {
      "filePath": "_protected/dashboard/account.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/audio": {
      "filePath": "_protected/dashboard/audio.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/canvas": {
      "filePath": "_protected/dashboard/canvas.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/chat": {
      "filePath": "_protected/dashboard/chat.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/notes": {
      "filePath": "_protected/dashboard/notes.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/transcribe": {
      "filePath": "_protected/dashboard/transcribe.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/": {
      "filePath": "_protected/dashboard/index.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/org/$orgId/": {
      "filePath": "_protected/dashboard/org/$orgId/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/org/$orgId/user/$userId": {
      "filePath": "_protected/dashboard/org/$orgId/user/$userId.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
