/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'

// Create Virtual Routes

const ProtectedDashboardIndexLazyImport = createFileRoute(
  '/_protected/dashboard/',
)()
const ProtectedDashboardTranscribeLazyImport = createFileRoute(
  '/_protected/dashboard/transcribe',
)()
const ProtectedDashboardChatLazyImport = createFileRoute(
  '/_protected/dashboard/chat',
)()
const ProtectedDashboardCanvasLazyImport = createFileRoute(
  '/_protected/dashboard/canvas',
)()
const ProtectedDashboardAudioLazyImport = createFileRoute(
  '/_protected/dashboard/audio',
)()
const ProtectedDashboardAccountLazyImport = createFileRoute(
  '/_protected/dashboard/account',
)()

// Create/Update Routes

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardIndexLazyRoute =
  ProtectedDashboardIndexLazyImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/index.lazy').then((d) => d.Route),
  )

const ProtectedDashboardTranscribeLazyRoute =
  ProtectedDashboardTranscribeLazyImport.update({
    id: '/dashboard/transcribe',
    path: '/dashboard/transcribe',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/transcribe.lazy').then(
      (d) => d.Route,
    ),
  )

const ProtectedDashboardChatLazyRoute = ProtectedDashboardChatLazyImport.update(
  {
    id: '/dashboard/chat',
    path: '/dashboard/chat',
    getParentRoute: () => ProtectedRoute,
  } as any,
).lazy(() =>
  import('./routes/_protected/dashboard/chat.lazy').then((d) => d.Route),
)

const ProtectedDashboardCanvasLazyRoute =
  ProtectedDashboardCanvasLazyImport.update({
    id: '/dashboard/canvas',
    path: '/dashboard/canvas',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/canvas.lazy').then((d) => d.Route),
  )

const ProtectedDashboardAudioLazyRoute =
  ProtectedDashboardAudioLazyImport.update({
    id: '/dashboard/audio',
    path: '/dashboard/audio',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/audio.lazy').then((d) => d.Route),
  )

const ProtectedDashboardAccountLazyRoute =
  ProtectedDashboardAccountLazyImport.update({
    id: '/dashboard/account',
    path: '/dashboard/account',
    getParentRoute: () => ProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_protected/dashboard/account.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/_protected/dashboard/account': {
      id: '/_protected/dashboard/account'
      path: '/dashboard/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof ProtectedDashboardAccountLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/audio': {
      id: '/_protected/dashboard/audio'
      path: '/dashboard/audio'
      fullPath: '/dashboard/audio'
      preLoaderRoute: typeof ProtectedDashboardAudioLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/canvas': {
      id: '/_protected/dashboard/canvas'
      path: '/dashboard/canvas'
      fullPath: '/dashboard/canvas'
      preLoaderRoute: typeof ProtectedDashboardCanvasLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/chat': {
      id: '/_protected/dashboard/chat'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof ProtectedDashboardChatLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/transcribe': {
      id: '/_protected/dashboard/transcribe'
      path: '/dashboard/transcribe'
      fullPath: '/dashboard/transcribe'
      preLoaderRoute: typeof ProtectedDashboardTranscribeLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexLazyImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteChildren {
  ProtectedDashboardAccountLazyRoute: typeof ProtectedDashboardAccountLazyRoute
  ProtectedDashboardAudioLazyRoute: typeof ProtectedDashboardAudioLazyRoute
  ProtectedDashboardCanvasLazyRoute: typeof ProtectedDashboardCanvasLazyRoute
  ProtectedDashboardChatLazyRoute: typeof ProtectedDashboardChatLazyRoute
  ProtectedDashboardTranscribeLazyRoute: typeof ProtectedDashboardTranscribeLazyRoute
  ProtectedDashboardIndexLazyRoute: typeof ProtectedDashboardIndexLazyRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardAccountLazyRoute: ProtectedDashboardAccountLazyRoute,
  ProtectedDashboardAudioLazyRoute: ProtectedDashboardAudioLazyRoute,
  ProtectedDashboardCanvasLazyRoute: ProtectedDashboardCanvasLazyRoute,
  ProtectedDashboardChatLazyRoute: ProtectedDashboardChatLazyRoute,
  ProtectedDashboardTranscribeLazyRoute: ProtectedDashboardTranscribeLazyRoute,
  ProtectedDashboardIndexLazyRoute: ProtectedDashboardIndexLazyRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/account': typeof ProtectedDashboardAccountLazyRoute
  '/dashboard/audio': typeof ProtectedDashboardAudioLazyRoute
  '/dashboard/canvas': typeof ProtectedDashboardCanvasLazyRoute
  '/dashboard/chat': typeof ProtectedDashboardChatLazyRoute
  '/dashboard/transcribe': typeof ProtectedDashboardTranscribeLazyRoute
  '/dashboard': typeof ProtectedDashboardIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/account': typeof ProtectedDashboardAccountLazyRoute
  '/dashboard/audio': typeof ProtectedDashboardAudioLazyRoute
  '/dashboard/canvas': typeof ProtectedDashboardCanvasLazyRoute
  '/dashboard/chat': typeof ProtectedDashboardChatLazyRoute
  '/dashboard/transcribe': typeof ProtectedDashboardTranscribeLazyRoute
  '/dashboard': typeof ProtectedDashboardIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_protected/dashboard/account': typeof ProtectedDashboardAccountLazyRoute
  '/_protected/dashboard/audio': typeof ProtectedDashboardAudioLazyRoute
  '/_protected/dashboard/canvas': typeof ProtectedDashboardCanvasLazyRoute
  '/_protected/dashboard/chat': typeof ProtectedDashboardChatLazyRoute
  '/_protected/dashboard/transcribe': typeof ProtectedDashboardTranscribeLazyRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/demo/tanstack-query'
    | '/dashboard/account'
    | '/dashboard/audio'
    | '/dashboard/canvas'
    | '/dashboard/chat'
    | '/dashboard/transcribe'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/demo/tanstack-query'
    | '/dashboard/account'
    | '/dashboard/audio'
    | '/dashboard/canvas'
    | '/dashboard/chat'
    | '/dashboard/transcribe'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/demo/tanstack-query'
    | '/_protected/dashboard/account'
    | '/_protected/dashboard/audio'
    | '/_protected/dashboard/canvas'
    | '/_protected/dashboard/chat'
    | '/_protected/dashboard/transcribe'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/forgot-password",
        "/reset-password",
        "/sign-in",
        "/demo/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/dashboard/account",
        "/_protected/dashboard/audio",
        "/_protected/dashboard/canvas",
        "/_protected/dashboard/chat",
        "/_protected/dashboard/transcribe",
        "/_protected/dashboard/"
      ]
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/_protected/dashboard/account": {
      "filePath": "_protected/dashboard/account.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/audio": {
      "filePath": "_protected/dashboard/audio.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/canvas": {
      "filePath": "_protected/dashboard/canvas.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/chat": {
      "filePath": "_protected/dashboard/chat.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/transcribe": {
      "filePath": "_protected/dashboard/transcribe.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/": {
      "filePath": "_protected/dashboard/index.lazy.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
